export { isNull } from './is-null'
export { isUndefined } from './is-undefined'
export { isNil } from './is-nil'
export { isNotNil } from './is-not-nil'
export { isBoolean } from './is-boolean'
export { isString } from './is-string'
export { isFunction } from './is-function'
export { isPrimitive } from './is-primitive'
